config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get "restricted", to: "pages#restricted"
  get "listings", to: "listings#index", as: "listings"
  post "listings", to: "listings#create"
  get "listings/new", to: "listings#new", as: "new_listing"
  get "listings/:id", to: "listings#show", as: "listing"
  put "listings/:id", to: "listings#update"
  patch "listings/:id", to: "listings#update"
  delete "listing/:id", to: "listing#destroy"
  get "listings/:id/edit", to: "listings#edit", as: "edit_listing"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :listings
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :listings
end

app/models/country.rb
class Country < ApplicationRecord
    has_many :listings
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :brand
  belongs_to :country

  has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :form_vars, only: [:new, :edit, :index, :show]
  

  def index
    @listings = Listing.all
  end

  def show
    
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_params)
    if @listing.save
        redirect_to @listing, notice: "Listing successfully created"
    else
      pp @listing.errors
      set_form_vars
      render "new", alert: "Something went wrong"
    end
  end

  def edit

  end

  def update
    @listing.update(listing_params)
    if @listing.save
        redirect_to @listing, notice: "Listing successfully updated"
    else
      pp @listing.errors
      set_form_vars
      render "edit", alert: "Something went wrong"
    end
  end

  def destroy
    @listing.destroy
    redirect_to listings_path, notice: "Listing successfully deleted"
  end
 
end


private 
def authorize_user
  if @listing.user_id != current_user.id
    flash[:alert] = "You don't have the required authorisation"
    redirect_to listings_path 
  end
end

def listing_params
  params.require(:listing).permit(:title, :brand_id, :year, :price, :category_id, :country_id, :description, :picture)
end

def set_listing
  @listing = Listing.find(params[:id])
end

def brand_names
  @brands = Brand.all
end

def form_vars
  @categories = Category.all
  # @categories = Listing.categories.keys
  @brands = Brand.all
  # @brands = Listing.brands.keys
  @countries = Country.all 
  # @countries = Listinbg.countries.keys
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :authenticate_user!, only: [:restricted]
    def home

    end

    def restricted

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def alert_subclass(input)
        case input
        when 'notice'
            return 'success'
        when 'alert'
            return 'warning'
        when 'error'
            return 'danger'
        else
            return 'info'
        end

    end
end

app/helpers/listings_helper.rb
module ListingsHelper

    def format_brand(brand)

    end

    def format_price(price)
        "$" + (price / 100).to_s
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhiskyLibrary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "pages", "listings", "data-turbo-track": "reload" %>
    <%# <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %> 
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <%flash.each do |key, value| %>
        <div class="alert alert-<%=alert_subclass(key)%> alert-dismissible fade show" role="alert">
          <%=value%>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%=form_with model: @listing, local: true do |f|%>
    <div class="form-group mb-3">
        <%=f.label :title, class: "form-label"%>
        <%=f.text_field :title%>
    </div>

    <div class="form-group mb-3">
        <%=f.label :brand_id, class: "form-label"%>
        <%=f.select :brand_id, @brands.map {|b| [b.name, b.id]}, class: "form-select"%>
    </div>

    <div class="form-group mb-3">
        <%=f.label :year, class: "form-label"%>
        <%=f.number_field :year%>
    </div>

    <div class="form-group mb-3">
        <%=f.label :price, class: "form-label"%>
        <%=f.number_field :price%>
    </div>

    <div class="form-group mb-3">
        <%=f.label :category_id, class: "form-label"%>
        <%=f.select :category_id, @categories.map {|m| [m.name, m.id]}, class: "form-select"%>
    </div>

    <div class="form-group mb-3">
        <%=f.label :country_id, class: "form-label"%>
        <%=f.select :country_id, @countries.map {|c| [c.name, c.id]}, class: "form-select"%>
    </div>
    
    <div class="form-group mb-3">
        <%=f.label :picture, class: "form-label"%>
        <%=f.file_field :picture, accept: "image/png,image/jpg,image/jpeg", class: "form-control"%>
    </div>

     <div class="form-group mb-3">
        <%=f.label :description, class: "form-label"%>
        <%=f.text_area :description, class: "form-control"%>
    </div>

    <div class="actions">
        <%=f.submit%>
    </div>
<%end%>

app/views/listings/edit.html.erb
<h1>Update Listing</h1>
<%= render "form"%>
<%link_to "Home", root_path%>

app/views/listings/index.html.erb
<section class="container">
<h1 class="display-3">Listings</h1>
    <section class="container">
        <div class="row row-cols-sm1 rows-cols-md2 row-cols-lg4">
            <%@listings.each do |listing|%>
                <div class="col mb-4">
                    <div class="card" style="width: 18rem;">
                        <%# <img src="..." class="card-img-top" alt="..."> %>
                        <%# <%=image_tag "placeholder.jpg", alt: "Whisky", class: "card-img-top" %> 
                         <%if listing.picture.attached?%>
                            <%=image_tag listing.picture, alt: listing.title, class: "thumbnail card-img top" %>
                        <%else%>
                            <%=image_tag "placeholder.jpg", alt: "Whisky", class: "thumbnail card-img top" %>
                        <%end%>
                        <div class="card-body">
                            <h5 class="card-title listing-title"><%=listing.title%></h5>
                            <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                            <p class="card-text"><%=listing.description%></p>
                            <div class="d-flex justify-content-between">
                                <h5><%=format_price(listing.price)%></h5>
                                <%=link_to "See More", listing_path(listing.id), class: "btn btn-outline-primary"%>
                            </div>
                        </div>
                    </div>
                </div>
            <%end%>
        </div>
    </section>
</section>

app/views/listings/new.html.erb
<h1>Create Listing</h1>
<%= render "form"%>
<%link_to "Home", root_path%>

app/views/listings/show.html.erb
<section class="container d-flex flex-column flex-md-row px-2 my-2 my-md-5">
    <div class="content col-12 col-md-7 col-lg-8 p-0 pr-md-3">
        <div class="col-12 p-0 main-preview mb-4">
        <%if @listing.picture.attached?%>
            <%=image_tag @listing.picture, alt: @listing.title, class: "thumbnail card-img top" %>
        <%else%>
            <%=image_tag "placeholder.jpg", alt: "Whisky", class: "thumbnail card-img top" %>
        <%end%>
        </div>
    </div>
    <div class="sidebar col-lg-4 p-0 mx-2 d-md-block">
        <h1 class="mb-sm-2 mb-md-5"><%=@listing.title%></h1>
        <h4 class="text-muted">Brand: <%=@listing.brand_id%></h4>
        <%puts `>>>> #{@listing.brand_id} <<<<` %>
        <h4 class="text-muted">Price: <%=format_price(@listing.price)%></h4>
        <h4 class="text-muted">Category: <%=@listing.category_id%></h4>
        <%= puts @listing.category_id %>
        <h4 class="text-muted">Description: <%=@listing.description%></h4>

        <div class="container">
        <%if current_user && current_user.id == @listing.user_id%>
            <div class="d-flex justify-content-equally">
                <%= link_to "Edit", edit_listing_path(@listing.id), class: "btn btn-warning mr-2" %>
                <%= link_to "Delete", @listing, method: :delete, class: "btn btn-danger mr-2", data: {confirm: "Are you sure you want to delete this listing?"} %>
            </div>
        <%end%>
    </div>
    </div>
</section>

app/views/pages/home.html.erb
<div class="main-background">
  <h1 class="display-2">Hello World</h1>
</div>

app/views/pages/restricted.html.erb
<h1>As a signed-in member you can see this secret page!<h1>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Whisky Collection</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%=root_path%>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
          <%# <%=link_to "About", about_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%=link_to "All Whiskey", listings_path, class: "nav-link" %>
          <%# # <%=link_to "All Whisky", class: "nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Countries
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">America</a></li>
            <li><a class="dropdown-item" href="#">Ireland</a></li>
            <li><a class="dropdown-item" href="#">Japan</a></li>
            <li><a class="dropdown-item" href="#">Scotland</a></li>
          </ul>
          </li>
            <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to "Create Listing", new_listing_path, class:"nav-link"  %>
            </li>
            <li class="nav-item">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, class:"nav-link"  %>
            </li>
            <% else %>
            <li class="nav-item">
                <%= link_to "Log In", new_user_session_path, class:"nav-link" %>
            </li>
            <% end %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>